/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedAiDashboardRouteRouteImport } from './routes/_authenticated/ai-dashboard/route'
import { Route as AuthenticatedViewAuditLogsIndexRouteImport } from './routes/_authenticated/view-audit-logs/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedManageVariablesIndexRouteImport } from './routes/_authenticated/manage-variables/index'
import { Route as AuthenticatedManageUserIndexRouteImport } from './routes/_authenticated/manage-user/index'
import { Route as AuthenticatedManageSecurityIndexRouteImport } from './routes/_authenticated/manage-security/index'
import { Route as AuthenticatedMaintenanceTabIndexRouteImport } from './routes/_authenticated/maintenance-tab/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAiDashboardWorkspaceRouteImport } from './routes/_authenticated/ai-dashboard/workspace'
import { Route as AuthenticatedAiDashboardSystemOverviewRouteImport } from './routes/_authenticated/ai-dashboard/system-overview'
import { Route as AuthenticatedAiDashboardRunDashboardRouteImport } from './routes/_authenticated/ai-dashboard/run-dashboard'
import { Route as AuthenticatedAiDashboardJobManagerRouteImport } from './routes/_authenticated/ai-dashboard/job-manager'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiDashboardRouteRoute =
  AuthenticatedAiDashboardRouteRouteImport.update({
    id: '/ai-dashboard',
    path: '/ai-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedViewAuditLogsIndexRoute =
  AuthenticatedViewAuditLogsIndexRouteImport.update({
    id: '/view-audit-logs/',
    path: '/view-audit-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedManageVariablesIndexRoute =
  AuthenticatedManageVariablesIndexRouteImport.update({
    id: '/manage-variables/',
    path: '/manage-variables/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManageUserIndexRoute =
  AuthenticatedManageUserIndexRouteImport.update({
    id: '/manage-user/',
    path: '/manage-user/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManageSecurityIndexRoute =
  AuthenticatedManageSecurityIndexRouteImport.update({
    id: '/manage-security/',
    path: '/manage-security/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMaintenanceTabIndexRoute =
  AuthenticatedMaintenanceTabIndexRouteImport.update({
    id: '/maintenance-tab/',
    path: '/maintenance-tab/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiDashboardWorkspaceRoute =
  AuthenticatedAiDashboardWorkspaceRouteImport.update({
    id: '/workspace',
    path: '/workspace',
    getParentRoute: () => AuthenticatedAiDashboardRouteRoute,
  } as any)
const AuthenticatedAiDashboardSystemOverviewRoute =
  AuthenticatedAiDashboardSystemOverviewRouteImport.update({
    id: '/system-overview',
    path: '/system-overview',
    getParentRoute: () => AuthenticatedAiDashboardRouteRoute,
  } as any)
const AuthenticatedAiDashboardRunDashboardRoute =
  AuthenticatedAiDashboardRunDashboardRouteImport.update({
    id: '/run-dashboard',
    path: '/run-dashboard',
    getParentRoute: () => AuthenticatedAiDashboardRouteRoute,
  } as any)
const AuthenticatedAiDashboardJobManagerRoute =
  AuthenticatedAiDashboardJobManagerRouteImport.update({
    id: '/job-manager',
    path: '/job-manager',
    getParentRoute: () => AuthenticatedAiDashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/ai-dashboard': typeof AuthenticatedAiDashboardRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/': typeof AuthenticatedIndexRoute
  '/ai-dashboard/job-manager': typeof AuthenticatedAiDashboardJobManagerRoute
  '/ai-dashboard/run-dashboard': typeof AuthenticatedAiDashboardRunDashboardRoute
  '/ai-dashboard/system-overview': typeof AuthenticatedAiDashboardSystemOverviewRoute
  '/ai-dashboard/workspace': typeof AuthenticatedAiDashboardWorkspaceRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/maintenance-tab': typeof AuthenticatedMaintenanceTabIndexRoute
  '/manage-security': typeof AuthenticatedManageSecurityIndexRoute
  '/manage-user': typeof AuthenticatedManageUserIndexRoute
  '/manage-variables': typeof AuthenticatedManageVariablesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/view-audit-logs': typeof AuthenticatedViewAuditLogsIndexRoute
}
export interface FileRoutesByTo {
  '/ai-dashboard': typeof AuthenticatedAiDashboardRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/': typeof AuthenticatedIndexRoute
  '/ai-dashboard/job-manager': typeof AuthenticatedAiDashboardJobManagerRoute
  '/ai-dashboard/run-dashboard': typeof AuthenticatedAiDashboardRunDashboardRoute
  '/ai-dashboard/system-overview': typeof AuthenticatedAiDashboardSystemOverviewRoute
  '/ai-dashboard/workspace': typeof AuthenticatedAiDashboardWorkspaceRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/maintenance-tab': typeof AuthenticatedMaintenanceTabIndexRoute
  '/manage-security': typeof AuthenticatedManageSecurityIndexRoute
  '/manage-user': typeof AuthenticatedManageUserIndexRoute
  '/manage-variables': typeof AuthenticatedManageVariablesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/view-audit-logs': typeof AuthenticatedViewAuditLogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/ai-dashboard': typeof AuthenticatedAiDashboardRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/ai-dashboard/job-manager': typeof AuthenticatedAiDashboardJobManagerRoute
  '/_authenticated/ai-dashboard/run-dashboard': typeof AuthenticatedAiDashboardRunDashboardRoute
  '/_authenticated/ai-dashboard/system-overview': typeof AuthenticatedAiDashboardSystemOverviewRoute
  '/_authenticated/ai-dashboard/workspace': typeof AuthenticatedAiDashboardWorkspaceRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/maintenance-tab/': typeof AuthenticatedMaintenanceTabIndexRoute
  '/_authenticated/manage-security/': typeof AuthenticatedManageSecurityIndexRoute
  '/_authenticated/manage-user/': typeof AuthenticatedManageUserIndexRoute
  '/_authenticated/manage-variables/': typeof AuthenticatedManageVariablesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/view-audit-logs/': typeof AuthenticatedViewAuditLogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/ai-dashboard'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/404'
    | '/500'
    | '/'
    | '/ai-dashboard/job-manager'
    | '/ai-dashboard/run-dashboard'
    | '/ai-dashboard/system-overview'
    | '/ai-dashboard/workspace'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/maintenance-tab'
    | '/manage-security'
    | '/manage-user'
    | '/manage-variables'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/view-audit-logs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ai-dashboard'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/404'
    | '/500'
    | '/'
    | '/ai-dashboard/job-manager'
    | '/ai-dashboard/run-dashboard'
    | '/ai-dashboard/system-overview'
    | '/ai-dashboard/workspace'
    | '/errors/$error'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/apps'
    | '/chats'
    | '/help-center'
    | '/maintenance-tab'
    | '/manage-security'
    | '/manage-user'
    | '/manage-variables'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/view-audit-logs'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/ai-dashboard'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/_authenticated/'
    | '/_authenticated/ai-dashboard/job-manager'
    | '/_authenticated/ai-dashboard/run-dashboard'
    | '/_authenticated/ai-dashboard/system-overview'
    | '/_authenticated/ai-dashboard/workspace'
    | '/_authenticated/errors/$error'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/maintenance-tab/'
    | '/_authenticated/manage-security/'
    | '/_authenticated/manage-user/'
    | '/_authenticated/manage-variables/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/view-audit-logs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-dashboard': {
      id: '/_authenticated/ai-dashboard'
      path: '/ai-dashboard'
      fullPath: '/ai-dashboard'
      preLoaderRoute: typeof AuthenticatedAiDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/view-audit-logs/': {
      id: '/_authenticated/view-audit-logs/'
      path: '/view-audit-logs'
      fullPath: '/view-audit-logs'
      preLoaderRoute: typeof AuthenticatedViewAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/manage-variables/': {
      id: '/_authenticated/manage-variables/'
      path: '/manage-variables'
      fullPath: '/manage-variables'
      preLoaderRoute: typeof AuthenticatedManageVariablesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage-user/': {
      id: '/_authenticated/manage-user/'
      path: '/manage-user'
      fullPath: '/manage-user'
      preLoaderRoute: typeof AuthenticatedManageUserIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manage-security/': {
      id: '/_authenticated/manage-security/'
      path: '/manage-security'
      fullPath: '/manage-security'
      preLoaderRoute: typeof AuthenticatedManageSecurityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maintenance-tab/': {
      id: '/_authenticated/maintenance-tab/'
      path: '/maintenance-tab'
      fullPath: '/maintenance-tab'
      preLoaderRoute: typeof AuthenticatedMaintenanceTabIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-dashboard/workspace': {
      id: '/_authenticated/ai-dashboard/workspace'
      path: '/workspace'
      fullPath: '/ai-dashboard/workspace'
      preLoaderRoute: typeof AuthenticatedAiDashboardWorkspaceRouteImport
      parentRoute: typeof AuthenticatedAiDashboardRouteRoute
    }
    '/_authenticated/ai-dashboard/system-overview': {
      id: '/_authenticated/ai-dashboard/system-overview'
      path: '/system-overview'
      fullPath: '/ai-dashboard/system-overview'
      preLoaderRoute: typeof AuthenticatedAiDashboardSystemOverviewRouteImport
      parentRoute: typeof AuthenticatedAiDashboardRouteRoute
    }
    '/_authenticated/ai-dashboard/run-dashboard': {
      id: '/_authenticated/ai-dashboard/run-dashboard'
      path: '/run-dashboard'
      fullPath: '/ai-dashboard/run-dashboard'
      preLoaderRoute: typeof AuthenticatedAiDashboardRunDashboardRouteImport
      parentRoute: typeof AuthenticatedAiDashboardRouteRoute
    }
    '/_authenticated/ai-dashboard/job-manager': {
      id: '/_authenticated/ai-dashboard/job-manager'
      path: '/job-manager'
      fullPath: '/ai-dashboard/job-manager'
      preLoaderRoute: typeof AuthenticatedAiDashboardJobManagerRouteImport
      parentRoute: typeof AuthenticatedAiDashboardRouteRoute
    }
  }
}

interface AuthenticatedAiDashboardRouteRouteChildren {
  AuthenticatedAiDashboardJobManagerRoute: typeof AuthenticatedAiDashboardJobManagerRoute
  AuthenticatedAiDashboardRunDashboardRoute: typeof AuthenticatedAiDashboardRunDashboardRoute
  AuthenticatedAiDashboardSystemOverviewRoute: typeof AuthenticatedAiDashboardSystemOverviewRoute
  AuthenticatedAiDashboardWorkspaceRoute: typeof AuthenticatedAiDashboardWorkspaceRoute
}

const AuthenticatedAiDashboardRouteRouteChildren: AuthenticatedAiDashboardRouteRouteChildren =
  {
    AuthenticatedAiDashboardJobManagerRoute:
      AuthenticatedAiDashboardJobManagerRoute,
    AuthenticatedAiDashboardRunDashboardRoute:
      AuthenticatedAiDashboardRunDashboardRoute,
    AuthenticatedAiDashboardSystemOverviewRoute:
      AuthenticatedAiDashboardSystemOverviewRoute,
    AuthenticatedAiDashboardWorkspaceRoute:
      AuthenticatedAiDashboardWorkspaceRoute,
  }

const AuthenticatedAiDashboardRouteRouteWithChildren =
  AuthenticatedAiDashboardRouteRoute._addFileChildren(
    AuthenticatedAiDashboardRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiDashboardRouteRoute: typeof AuthenticatedAiDashboardRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedMaintenanceTabIndexRoute: typeof AuthenticatedMaintenanceTabIndexRoute
  AuthenticatedManageSecurityIndexRoute: typeof AuthenticatedManageSecurityIndexRoute
  AuthenticatedManageUserIndexRoute: typeof AuthenticatedManageUserIndexRoute
  AuthenticatedManageVariablesIndexRoute: typeof AuthenticatedManageVariablesIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedViewAuditLogsIndexRoute: typeof AuthenticatedViewAuditLogsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiDashboardRouteRoute:
    AuthenticatedAiDashboardRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedMaintenanceTabIndexRoute: AuthenticatedMaintenanceTabIndexRoute,
  AuthenticatedManageSecurityIndexRoute: AuthenticatedManageSecurityIndexRoute,
  AuthenticatedManageUserIndexRoute: AuthenticatedManageUserIndexRoute,
  AuthenticatedManageVariablesIndexRoute:
    AuthenticatedManageVariablesIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedViewAuditLogsIndexRoute: AuthenticatedViewAuditLogsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
